Migrate landing to typescript
Reinforz-Github/reinforz-landing pull request #57
Opened 2023-02-17 12:43 UTC by paradus-hex

2023-02-17 13:40 UTC, imoxto commented on src/components/AboutUs.tsx
> +              weren't alone. Our classNamemates felt the same way.
rename

2023-02-18 12:29 UTC, arionrefat commented on src/components/Features.tsx
>  import { featureSection } from '../constants/constants.js';
It's not a js file anymore

2023-02-18 12:32 UTC, arionrefat commented on src/components/Features.tsx
>  import { featureSection } from '../constants/constants.js';
Update the `constants.js`

2023-02-18 12:33 UTC, arionrefat requested changes

2023-02-18 12:33 UTC, arionrefat commented on src/components/Features.tsx
>  import { featureSection } from '../constants/constants.js';
change the `constants.js`

2023-02-18 14:12 UTC, merged